# Generated by Django 2.2.7 on 2020-04-15 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(max_length=100)),
                ('proj_fullname', models.CharField(max_length=100)),
                ('proj_date', models.DateField()),
                ('proj_cover_img', models.ImageField(upload_to='proj_cover_img')),
                ('display_on_main', models.BooleanField(default=True)),
                ('proj_description', models.TextField(help_text='can use HTML tags', max_length=2500)),
                ('projPage_Img1', models.ImageField(blank=True, help_text='can keep blank', upload_to='proj_Img')),
                ('projPage_Img2', models.ImageField(blank=True, help_text='can keep blank', upload_to='proj_Img')),
                ('projPage_Img3', models.ImageField(blank=True, help_text='can keep blank', upload_to='proj_Img')),
                ('projPage_Img4', models.ImageField(blank=True, help_text='can keep blank', upload_to='proj_Img')),
                ('projPage_Img5', models.ImageField(blank=True, help_text='can keep blank', upload_to='proj_Img')),
            ],
        ),
    ]
